sig_source:
  tx_script: experiments/sig_source/tx.py
  rx_script: experiments/sig_source/rx.py
  analyze_script: experiments/sig_source/analyze.py

  metrics: [frequency_error, amplitude_error]

  thresholds:
    frequency_error: 1.0
    amplitude_error: 5.0

  input_options:
    # [waveform, frequency, amplitude, duration]
    - [sine,     1000, 1.0, 10]
    - [cosine,   2000, 0.8, 10]
    - [square,    500, 1.2, 10]
    - [triangle, 1500, 0.6, 10]